services:
  accesslog:
    image: diamol/ch18-access-log
    ports:
      - "8030:80"
    volumes:
      - ./access-log/config/test:/app/config-override
    networks:
      - iotd-net

  iotd:
    image: diamol/ch18-image-of-the-day
    ports:
      - "8020:80"
    environment:
      CONFIG_SOURCE_PATH: /app/config-override/application.properties
    volumes:
      - ./image-of-the-day/config/test:/app/config-override
    networks:
      - iotd-net

  image-gallery:
    image: diamol/ch18-image-gallery
    ports:
      - "8010:80"
    volumes:
      - ./image-gallery/config/test:/app/config-override
    depends_on:
      - accesslog
      - iotd
    networks:
      - iotd-net

networks:
  iotd-net:
